version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # Change target to 'production' if you want to use npm in the host machine instead of in the container.
      target: dev
    env_file:
      - .env.defaults
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: portfolio.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    image: portfolio
    ports:
      - "8000:8000"
    volumes:
      # Don't use an umbrella `.:/app` to mount the whole project directory. 
      # When you bind-mount a directory into a non-empty directory on the container, the existing contents 
      # will be obscured by the bind mount. 
      # See https://docs.docker.com/storage/bind-mounts/#mount-into-a-non-empty-directory-on-the-container
      - ./portfolio:/app/portfolio
      - ./static_src:/app/static_src
      
      # Uncomment the following line if you use npm on host machine instead of in the container.
      # - ./static_compiled:/app/static_compiled

      # Database and Media files:
      # Mounting the '/data' directory makes it easier to backup and restore 
      # database and media files and provides persistence when rebuilding the container.
      - ./data:/app/data

      # Frontend config:
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js
    stdin_open: true
    tty: true
