version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: victoriachan.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    image: victoriachan
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
