# fly.toml app configuration file generated for vc-portfolio on 2024-05-03T16:10:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vc-portfolio'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]
  build-target = "production"

[experimental]
  auto_rollback = true

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Mount sqlite database and media files in a volume so we have persistance across deploys.
# Created using `fly volumes create vc_portfolio_volume -r lhr`
[[mounts]]
  source = "vc_portfolio_volume"
  destination = "/data"
  processes = ["app"]

[[statics]]
  # Uses destination from the mount above.
  # Make sure to set MEDIA_DIR environment variable to be same as the guest_path.
  # Set MEDIA_DIR to '/app/data/media' in environment variables.
  guest_path = "/data/media"
  url_prefix = "/media/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "/venv/bin/python manage.py migrate --noinput"
