name: CI

on:
  push

jobs:  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1

  compile_static:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --no-audit
      - run: npm run build-prod
      - uses: actions/upload-artifact@v4
        with:
          name: static
          path: static_compiled/
          
  test_python:
    needs: compile_static
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: portfolio.settings.test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: static
          path: static_compiled/
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Collect static assets
        run: |
          python manage.py collectstatic --noinput --verbosity 3 --clear
      - name: Run system checks
        run: |
          python manage.py check
      - name: Check migration conflict
        run: |
          python manage.py makemigrations --check --noinput
      - name: Create cache table
        run: python manage.py createcachetable
      - name: Test
        run: python manage.py test
