name: Fly Deploy

concurrency:
    group: production
    cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore: ['docs/**']

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
